### ISSUE TITLE
Doesn't work for Linux

### ISSUE THREAD

**Issue by iBuseWinner** [games647/LambdaAttack#39]
Hi, I have an error in console when trying to launch bots from my VDS.

`Apr 11, 2020 12:06:17 AM com.github.games647.lambdaattack.LambdaAttack lambda$main$0
SEVERE: null
java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
        at java.desktop/java.awt.Window.initGC(Window.java:487)
        at java.desktop/java.awt.Window.init(Window.java:507)
        at java.desktop/java.awt.Window.<init>(Window.java:549)
        at java.desktop/java.awt.Frame.<init>(Frame.java:423)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
        at com.github.games647.lambdaattack.gui.MainGui.<init>(MainGui.java:31)
        at com.github.games647.lambdaattack.LambdaAttack.main(LambdaAttack.java:37)`

**Comment by games647** [comment]
Which display server do you use? Is it possible that you use Wayland?

**Comment by iBuseWinner** [comment]
Do I need to use Wayland to run this program?

**Comment by games647** [comment]
No, but I thought you were using it. Please check if the display variable is correctly pointing to the correct display server connection.

**Comment by hajdulak** [comment]
I kinda thought you were supposed to be able to run it without any graphical interface?
I followed your instructions in the "Command Line Usage" section to run LambdaAttack without a GUI, but I've received a very similar error.
`No X11 DISPLAY variable was set, but this program performed an operation which requires it.`

I have no display server installed and I'm not planning on doing so anytime soon.
I'm not sure what caused this error, but running without a GUI shouldn't require a display server I guess.

**Comment by games647** [comment]
>I kinda thought you were supposed to be able to run it without any graphical interface?

No it's not required, but I didn't know that the first post is about running it from the command line. I thought it's about running it using the GUI with X11-Forwarding, since it mentions the display variable.

>I have no display server installed and I'm not planning on doing so anytime soon.
I'm not sure what caused this error, but running without a GUI shouldn't require a display server I guess.

I guess you are running the version from the releases page? Then it's very outdated. It doesn't contain the newest changes. I'll make a new release.
